using System.Collections.Generic;

namespace RimWorldTestHarness.Shared;

// Turns the SpawnAnimal step's args into plain geometry: a PawnKindDef name plus the anchor-relative
// cells to drop animals on. Pure string/number work with no Verse dependency, so the whole vocabulary
// is unit-testable offline and Mod/SceneBuilder.SpawnAnimals stays a thin adapter that only resolves
// the def and calls PawnGenerator/GenSpawn — the same split PlaceThings uses (see SceneLayout).
//
// Why animals get their own planner rather than riding PlaceThings: a pawn is not built by
// ThingMaker.MakeThing, it is generated by PawnGenerator, and it has no `stuff`, no meaningful `rot`,
// and no `clear` semantics (an animal is passable, so it never needs a footprint bulldozed). Forcing
// it through PlaceThings' grammar would mean validating args that can't apply. The two DO share the
// anchor grammar, though, so ReadAnchor is reused rather than reimplemented.
//
// Placement is a single row along +x from the anchor, `spacing` cells apart. A row keeps N animals
// legible in one screenshot without stacking them on one cell, and count=1 collapses to just the
// anchor cell — which is the common case ("spawn a muffalo at centre").
public static class AnimalLayout
{
    // One animal, one cell apart from the next but two cells clear so bodies don't visually overlap.
    public const int DefaultCount = 1;
    public const int DefaultSpacing = 2;

    // A fat-fingered count must not turn a screenshot run into a several-dozen-pawn spawn that tanks
    // the framerate the screenshots depend on — the same guard reason as SceneLayout.MaxPlacements,
    // set far lower because a generated pawn is much heavier than a spawned wall.
    public const int MaxCount = 64;

    private static readonly string[] KnownArgs =
    {
        StepArgs.SpawnAnimalKind,
        StepArgs.SpawnAnimalCount,
        StepArgs.SpawnAnimalSpacing,
        StepArgs.SceneAnchor,
        StepArgs.SceneOffset,
        StepArgs.SceneUnfog,
        StepArgs.SceneClear,
    };

    // Returns false with a specific reason rather than throwing, so a malformed scenario yields a
    // readable report entry instead of an exception during mod startup (which would leave
    // Runner/run_test.sh waiting on a report file that never appears).
    public static bool TryPlan(
        IReadOnlyDictionary<string, string> args,
        out AnimalPlan plan,
        out string? error)
    {
        plan = new AnimalPlan();

        if (!ArgReader.ValidateKnownArgs(args, KnownArgs, out error))
            return false;
        if (!ReadKind(args, out plan.KindDefName, out error))
            return false;
        if (!SceneLayout.ReadAnchor(args, plan, out error))
            return false;
        if (!SceneLayout.ReadPositive(args, StepArgs.SpawnAnimalCount, DefaultCount, out int count, out error))
            return false;
        if (!SceneLayout.ReadPositive(args, StepArgs.SpawnAnimalSpacing, DefaultSpacing, out int spacing, out error))
            return false;
        if (!ArgReader.TryReadBool(args, StepArgs.SceneUnfog, SceneLayout.DefaultUnfog, out plan.Unfog, out error))
            return false;
        if (!ArgReader.TryReadBool(args, StepArgs.SceneClear, SceneLayout.DefaultClear, out plan.Clear, out error))
            return false;

        if (count > MaxCount)
        {
            error = $"'{StepArgs.SpawnAnimalCount}' is {count}, over the {MaxCount} cap — spawning that " +
                    "many pawns would tank the framerate the screenshot depends on";
            return false;
        }

        for (int i = 0; i < count; i++)
            plan.Cells.Add(new ScenePlacement(i * spacing, 0));

        error = null;
        return true;
    }

    // The def is only NAME-checked here; whether it resolves to a real, animal PawnKindDef needs the
    // DefDatabase, so the adapter does that and reports a missing or non-animal kind. Keeping it out of
    // the pure planner is what lets these tests run with no game loaded.
    private static bool ReadKind(
        IReadOnlyDictionary<string, string> args, out string kind, out string? error)
    {
        kind = ArgReader.ReadString(args, StepArgs.SpawnAnimalKind, "");
        if (string.IsNullOrWhiteSpace(kind))
        {
            error = $"'{StepArgs.SpawnAnimalKind}' is required and must not be empty";
            return false;
        }

        error = null;
        return true;
    }
}

// A resolved SpawnAnimal plan: which animal, where its row sits, and whether to lift fog so it is
// actually visible. Carries anchor/offset via IAnchoredPlan so SceneLayout.ReadAnchor fills it in.
public sealed class AnimalPlan : IAnchoredPlan
{
    public string KindDefName = "";

    // Lift fog over the map after spawning, so the animals are actually drawn. Same hazard as
    // PlaceThings: RimWorld draws nothing in fogged cells, so a scene built at map centre on a fresh
    // colony is invisible while every step still reports success. See StepArgs.SceneUnfog.
    public bool Unfog = SceneLayout.DefaultUnfog;

    // Clear each spawn cell of destroyable things and roof before spawning, so an animal can land on a
    // cell a wall or rock would otherwise refuse. Opt-in (default false), same as PlaceThings/SetTerrain
    // and for the same reason: clearing permanently destroys map content. See StepArgs.SceneClear.
    public bool Clear = SceneLayout.DefaultClear;

    // One entry per animal, as an anchor-relative offset. The adapter resolves the anchor against a
    // live Map and reports any cell that refused its pawn, so a partial spawn is never silent.
    public readonly List<ScenePlacement> Cells = new List<ScenePlacement>();

    public SceneAnchorKind Anchor { get; set; }
    public int AnchorX { get; set; }
    public int AnchorZ { get; set; }
    public int OffsetX { get; set; }
    public int OffsetZ { get; set; }
}
