using System.Collections.Generic;
using System.Globalization;

namespace RimWorldTestHarness.Shared;

// Turns the SpawnPawn step's args into plain data: a PawnKindDef name, a faction selector, an
// optional gender, a parsed hediff list, and the anchor-relative cells to drop pawns on. Pure
// string/number work with no Verse dependency, so the whole vocabulary is unit-testable offline and
// Mod/SceneBuilder.SpawnPawns stays a thin adapter that only resolves defs and calls
// PawnGenerator/GenSpawn — the same split PlaceThings uses (see SceneLayout).
//
// Why pawns get their own planner rather than riding PlaceThings: a pawn is not built by
// ThingMaker.MakeThing, it is generated by PawnGenerator, and it has no `stuff` or `rot`. The two DO
// share the anchor grammar, though, so ReadAnchor is reused rather than reimplemented.
//
// Placement is a single row along +x from the anchor, `spacing` cells apart. A row keeps N pawns
// legible in one screenshot without stacking them on one cell, and count=1 collapses to just the
// anchor cell — which is the common case ("spawn a colonist at centre").
public static class PawnLayout
{
    // One pawn, two cells clear so bodies don't visually overlap.
    public const int DefaultCount = 1;
    public const int DefaultSpacing = 2;

    // A fat-fingered count must not turn a screenshot run into a several-dozen-pawn spawn that tanks
    // the framerate the screenshots depend on — the same guard reason as SceneLayout.MaxPlacements,
    // set far lower because a generated pawn is much heavier than a spawned wall.
    public const int MaxCount = 64;

    // faction selector values. "wild" is the default so bare "spawn a muffalo" needs no faction key.
    public const string FactionWild = "wild";
    public const string FactionPlayer = "player";
    public const string FactionHostile = "hostile";
    public const string DefaultFaction = FactionWild;

    public const string GenderMale = "male";
    public const string GenderFemale = "female";

    // '@' targets a body part, ':' sets a severity. Neither can appear in a defName, so splitting on
    // them is unambiguous.
    private const char PartMarker = '@';
    private const char SeverityMarker = ':';

    private static readonly string[] KnownArgs =
    {
        StepArgs.SpawnPawnKind,
        StepArgs.SpawnPawnCount,
        StepArgs.SpawnPawnSpacing,
        StepArgs.SpawnPawnFaction,
        StepArgs.SpawnPawnGender,
        StepArgs.SpawnPawnHediffs,
        StepArgs.SceneAnchor,
        StepArgs.SceneOffset,
        StepArgs.SceneUnfog,
        StepArgs.SceneClear,
    };

    // Returns false with a specific reason rather than throwing, so a malformed scenario yields a
    // readable report entry instead of an exception during mod startup (which would leave
    // Runner/run_test.sh waiting on a report file that never appears).
    public static bool TryPlan(
        IReadOnlyDictionary<string, string> args,
        out PawnPlan plan,
        out string? error)
    {
        plan = new PawnPlan();

        if (!ArgReader.ValidateKnownArgs(args, KnownArgs, out error))
            return false;
        if (!ReadKind(args, out plan.KindDefName, out error))
            return false;
        if (!ReadFaction(args, out plan.Faction, out error))
            return false;
        if (!ReadGender(args, out plan.Gender, out error))
            return false;
        if (!ReadHediffs(args, plan.Hediffs, out error))
            return false;
        if (!SceneLayout.ReadAnchor(args, plan, out error))
            return false;
        if (!SceneLayout.ReadPositive(args, StepArgs.SpawnPawnCount, DefaultCount, out int count, out error))
            return false;
        if (!SceneLayout.ReadPositive(args, StepArgs.SpawnPawnSpacing, DefaultSpacing, out int spacing, out error))
            return false;
        if (!ArgReader.TryReadBool(args, StepArgs.SceneUnfog, SceneLayout.DefaultUnfog, out plan.Unfog, out error))
            return false;
        if (!ArgReader.TryReadBool(args, StepArgs.SceneClear, SceneLayout.DefaultClear, out plan.Clear, out error))
            return false;

        if (count > MaxCount)
        {
            error = $"'{StepArgs.SpawnPawnCount}' is {count}, over the {MaxCount} cap — spawning that " +
                    "many pawns would tank the framerate the screenshot depends on";
            return false;
        }

        for (int i = 0; i < count; i++)
            plan.Cells.Add(new ScenePlacement(i * spacing, 0));

        error = null;
        return true;
    }

    // The def is only NAME-checked here; whether it resolves to a real PawnKindDef needs the
    // DefDatabase, so the adapter does that. Keeping it out of the pure planner is what lets these
    // tests run with no game loaded.
    private static bool ReadKind(
        IReadOnlyDictionary<string, string> args, out string kind, out string? error)
    {
        kind = ArgReader.ReadString(args, StepArgs.SpawnPawnKind, "");
        if (string.IsNullOrWhiteSpace(kind))
        {
            error = $"'{StepArgs.SpawnPawnKind}' is required and must not be empty";
            return false;
        }

        error = null;
        return true;
    }

    // Validated against the three known values rather than passed through, so a "player " typo or
    // "enemy" fails the scenario instead of silently falling back to wild — the plausible-but-wrong
    // failure this harness exists to catch.
    private static bool ReadFaction(
        IReadOnlyDictionary<string, string> args, out SpawnFaction faction, out string? error)
    {
        string raw = ArgReader.ReadString(args, StepArgs.SpawnPawnFaction, DefaultFaction);
        error = null;
        switch (raw)
        {
            case FactionWild:
                faction = SpawnFaction.Wild;
                return true;
            case FactionPlayer:
                faction = SpawnFaction.Player;
                return true;
            case FactionHostile:
                faction = SpawnFaction.Hostile;
                return true;
            default:
                faction = SpawnFaction.Wild;
                error = $"'{StepArgs.SpawnPawnFaction}' must be one of " +
                        $"{FactionWild}/{FactionPlayer}/{FactionHostile} (got '{raw}')";
                return false;
        }
    }

    // Absent means "let generation pick", which is why this returns Unset rather than defaulting to a
    // gender: forcing one when the scenario didn't ask would quietly bias every generated body.
    private static bool ReadGender(
        IReadOnlyDictionary<string, string> args, out SpawnGender gender, out string? error)
    {
        error = null;
        if (!args.TryGetValue(StepArgs.SpawnPawnGender, out string? raw))
        {
            gender = SpawnGender.Unset;
            return true;
        }

        switch (raw)
        {
            case GenderMale:
                gender = SpawnGender.Male;
                return true;
            case GenderFemale:
                gender = SpawnGender.Female;
                return true;
            default:
                gender = SpawnGender.Unset;
                error = $"'{StepArgs.SpawnPawnGender}' must be {GenderMale} or {GenderFemale} (got '{raw}')";
                return false;
        }
    }

    // Parses the "Def[@Part][:severity]; ..." list into plain specs. Def resolution and body-part
    // lookup happen in the adapter against a real DefDatabase and the kind's body; this only splits
    // the grammar and validates the shape, so an empty def name or an unparseable severity fails the
    // scenario at load rather than mid-run.
    private static bool ReadHediffs(
        IReadOnlyDictionary<string, string> args, List<HediffSpec> into, out string? error)
    {
        error = null;
        string raw = ArgReader.ReadString(args, StepArgs.SpawnPawnHediffs, "");
        if (string.IsNullOrWhiteSpace(raw))
            return true;

        foreach (string entry in raw.Split(';'))
        {
            string trimmed = entry.Trim();
            if (trimmed.Length > 0 && !TryParseHediff(trimmed, into, out error))
                return false;
        }

        return true;
    }

    private static bool TryParseHediff(string entry, List<HediffSpec> into, out string? error)
    {
        string body = entry;

        // Severity is peeled off the end first because it's marked by ':' and a body part can't
        // contain one, so what's left is cleanly "Def" or "Def@Part".
        float? severity = null;
        int severityAt = body.IndexOf(SeverityMarker);
        if (severityAt >= 0)
        {
            string severityText = body.Substring(severityAt + 1).Trim();
            if (!float.TryParse(severityText, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) ||
                parsed <= 0f)
            {
                error = $"hediff '{entry}' has an invalid severity '{severityText}' — expected a number greater than 0";
                return false;
            }

            severity = parsed;
            body = body.Substring(0, severityAt).Trim();
        }

        string? bodyPart = null;
        int partAt = body.IndexOf(PartMarker);
        if (partAt >= 0)
        {
            bodyPart = body.Substring(partAt + 1).Trim();
            body = body.Substring(0, partAt).Trim();
            if (bodyPart.Length == 0)
            {
                error = $"hediff '{entry}' names a body part with '@' but leaves it empty";
                return false;
            }
        }

        if (body.Length == 0)
        {
            error = $"hediff '{entry}' has no HediffDef name";
            return false;
        }

        into.Add(new HediffSpec(body, bodyPart, severity));
        error = null;
        return true;
    }
}

// Which faction a spawned pawn belongs to. Resolved to a real Faction by the adapter, the only place
// that can see the live FactionManager.
public enum SpawnFaction
{
    Wild,    // no faction — animals, wild men
    Player,  // the colony
    Hostile, // a deterministic enemy faction of the player
}

// Forced gender, or Unset to let generation choose.
public enum SpawnGender
{
    Unset,
    Male,
    Female,
}

// One health condition to apply, as parsed from the scenario. The def name and optional body-part
// name are resolved by the adapter; severity null means "use the def's default".
public sealed class HediffSpec
{
    public readonly string DefName;
    public readonly string? BodyPartDefName;
    public readonly float? Severity;

    public HediffSpec(string defName, string? bodyPartDefName, float? severity)
    {
        DefName = defName;
        BodyPartDefName = bodyPartDefName;
        Severity = severity;
    }
}

// A resolved SpawnPawn plan: which kind, which faction, forced gender, health conditions, where the
// row sits, and whether to clear/unfog. Carries anchor/offset via IAnchoredPlan so
// SceneLayout.ReadAnchor fills it in.
public sealed class PawnPlan : IAnchoredPlan
{
    public string KindDefName = "";
    public SpawnFaction Faction = SpawnFaction.Wild;
    public SpawnGender Gender = SpawnGender.Unset;
    public readonly List<HediffSpec> Hediffs = new List<HediffSpec>();

    // Lift fog over the map after spawning, so the pawns are actually drawn. Same hazard as
    // PlaceThings: RimWorld draws nothing in fogged cells, so a scene built at map centre on a fresh
    // colony is invisible while every step still reports success. See StepArgs.SceneUnfog.
    public bool Unfog = SceneLayout.DefaultUnfog;

    // Clear each spawn cell of destroyable things and roof before spawning, so a pawn can land on a
    // cell a wall or rock would otherwise refuse. Opt-in (default false), same as PlaceThings. See
    // StepArgs.SceneClear.
    public bool Clear = SceneLayout.DefaultClear;

    // One entry per pawn, as an anchor-relative offset. The adapter resolves the anchor against a
    // live Map and reports any cell that refused its pawn, so a partial spawn is never silent.
    public readonly List<ScenePlacement> Cells = new List<ScenePlacement>();

    public SceneAnchorKind Anchor { get; set; }
    public int AnchorX { get; set; }
    public int AnchorZ { get; set; }
    public int OffsetX { get; set; }
    public int OffsetZ { get; set; }
}
